name: mega_ai
description: MEGA AI Ultimate Assistant
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  speech_to_text: ^6.5.1
  flutter_tts: ^4.0.2
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.6
flutter:
  uses-material-design: true
